services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_dev
    container_name: 'anki-web'
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file: 
      - .env_dev
      - .env
    depends_on:
      - postgres
    tty: true
    volumes:
      - ./Django:/opt/webapp
  react:
    image: node:18
    volumes:
      - ./React:/opt/react-front
      - ./Django/static:/opt/react-front/dist
    tty: true
    container_name: 'react'
    working_dir: /opt/react-front
    environment:
      - 'DEVELOPMENT': 'True'
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: anki
      TZ: "Asia/Tokyo"
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"